### ISSUE TITLE
Can't push new branch

### ISSUE THREAD

**Issue by yevhen-sapsai** [alegaagafonov/nodejscourse#1]
$ git push --set-upstream origin yevhen_sapsai_hw_1
ERROR: Permission to alegaagafonov/nodejscourse.git denied to yevhen-sapsai.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by alegaagafonov** [comment]
added to collaborators - is it still relevant?

**Comment by yevhen-sapsai** [comment]
Works fine, home work is pushed!
